import React from 'react';
import img from '../media/web.svg'; 
import img4 from '../media/consultation.svg';
import { Link } from 'react-router-dom';

const Services = () => {

    return (
        <div id="services" className="bg-neutral-950 py-12" >
            <section data-aos="zoom-in-down">
                    <div className="my-4 py-4">
                        <h2 className="my-2 text-center text-3xl text-sky-50 uppercase font-bold">services</h2>
                        <div className='flex justify-center'>
                            <div className='w-24 border-b-4 border-blue-300'></div>
                        </div>
                    </div>

                    <div className="px-12" data-aos="fade-down" data-aos-delay="600">
                        <div className="grid grid-cols-2 justify-items-center gap-10">
                            
                            <div className="bg-cyan-950 transition-all ease-in-out duration-400 overflow-hidden text-sky-59 hover:bg-sky-800 hover:text-neutral-50 rounded-lg shadow-2xl p-3 group flex flex-col items-center">
                                <img alt="card img" className="rounded-t group-hover:scale-[1.15] transition duration-1000 ease-in-out" src={img} />
                                <div className="m-2 text-justify text-sm w-full">
                                <h2 className="font-semibold my-4 text-2xl text-white text-center">DCF Generator</h2>
                                <p className="text-md font-medium text-white">
                                    The DCF Generator stands as an emblem of precision in financial tools. Enter any company's stock ticker and receive a meticulously crafted DCF detailing its financial trajectory. Designed for both novice and expert investors, this tool simplifies the complexities of financial forecasting, presenting data seamlessly.
                                </p>
                                <div className="flex justify-center mt-4 gap-2">
                                    <Link to="/create" className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded transition duration-300 ease-in-out">
                                        Start Creating Now!
                                    </Link>
                                </div>
                                </div>
                            </div>

                            <div className="bg-cyan-950 transition-all ease-in-out duration-400 overflow-hidden text-sky-59 hover:bg-sky-800 hover:text-neutral-950 rounded-lg shadow-2xl p-3 group flex flex-col items-center">
                                <img alt="card img" className="rounded-t group-hover:scale-[1.15] transition duration-1000 ease-in-out" src={img4} />
                                <div className="m-2 text-justify text-sm w-full">
                                <h2 className="font-semibold my-4 text-2xl text-white text-center">LLM Chatbot</h2>
                                <p className="text-md font-medium text-white">
                                    The LLM Chatbot is a pioneering tool designed to assist with in-depth financial analysis. Simply input any DCF—whether generated by us or elsewhere—and engage the chatbot with questions. It excels in providing insightful evaluations of a company's financial standing, summarizing critical data, and guiding users through their analysis with clarity and precision.
                                </p>
                                <div className="flex justify-center mt-4 gap-2">
                                    <Link to="/analyze" className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded transition duration-300 ease-in-out">
                                        Let's Try Analyzing!
                                    </Link>
                                </div>
                                </div>
                            </div>
                        </div>
                    </div>
            </section>
        </div>
    )
}

export default Services;